os:
  - linux
sudo: false
addons:
  apt:
    # Flutter depends on /usr/lib/x86_64-linux-gnu/libstdc++.so.6 version GLIBCXX_3.4.18
    sources:
      - ubuntu-toolchain-r-test # if we don't specify this, the libstdc++6 we get is the wrong version
    packages:
      - libstdc++6
      - fonts-droid-fallback
before_script:
  - git clone https:/github.com/flutter/flutter.git -b stable
  - ./flutter/bin/flutter doctor
script:
  - ./flutter/bin/flutter test
cache:
  directories:
    - $HOME/.pub-cache
notifications:
  slack:
    secure: Lg+m7Koy66CREqcsRxtZad63ddpQqmtl1hqyp3OiJHjL7lzL4cGne3pQGEQBTJUENQTgIAPQMT3j97Ufz44mLjUyKcJItVFYrgguAhRwDTw/G3MhKd2IptMY9495h7Qz5JlIT5nF4fch2JeM1guKvP8pzVcWLhB+oSgr9oICyAqoKNXRSALVlv0DbMIzHnEQFvvmkh5EY2UuSJOpXWAXr02eYWMMxsgn2KZEGuE7L3/RtuSDjE6t4kbU59lcma+vfDanN+a/eljkLarVobqZcQ8WcBNEcGHK6wRq/6gvV8IwOkbfwqJaT0Ai0XDk+7r3wVkffYT5AfZpR+XEQ6jCmjrbPTBSzE+P6ljn73rsqd6s5ptKASP2LL+8XJ03dEFhJzban6NGKOrxdCuUfIEh+eyEt/Kndy/yARxCBKwFEVXyg7s/YOpz3ZpoqfPcyT4H4PbyC3jpuEyPq00fJ9n48HcO43Q04cttUxk1T4t6uvgxXL63GuHt+zI0tlpp9obXdUTql9UdrqKRh69pDOwPfbpEnAqKJak8W4DJ12YPV5x8WEXyLMEh42FwAFi53G1PAsSmKK+kSjKfyoNkCKWpOvjyZXA6WMcSHofSrfZLZBoRrW3in06uvwFlBa3mxH7FiVHlYEQK8j8cyQQEHsik+tx80sP8+BEIclBjkSeInek=
