os:
- linux
sudo: false
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - libstdc++6
    - fonts-droid-fallback
before_script:
- git clone https://github.com/flutter/flutter.git -b stable
- "./flutter/bin/flutter doctor"
script:
- "./flutter/bin/flutter test"
cache:
  directories:
  - "$HOME/.pub-cache"
notifications:
  slack:
    - opensourceflu-w4s5951:8301j0xeXARwLxeh6d3dDlQO#testing
